drop table if exists comanda cascade;
drop table if exists cardapio cascade;
drop table if exists itens cascade;


CREATE TABLE comanda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TIMESTAMP NOT NULL,
    nr_mesa BIGINT NOT NULL,
    nm_cliente VARCHAR(180) NOT NULL
);

CREATE TABLE cardapio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cafe VARCHAR(150) NOT NULL UNIQUE,
    descricao VARCHAR(220) NOT NULL,
    preco NUMERIC(10, 2) NOT NULL
);

CREATE TABLE itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_comanda BIGINT NOT NULL,
    id_cardapio BIGINT NOT NULL,
    qtd BIGINT NOT NULL CHECK (qtd > 0),
    CONSTRAINT fk_itens_comanda FOREIGN KEY (id_comanda) REFERENCES comanda (id),
    CONSTRAINT fk_itens_cardapio FOREIGN KEY (id_cardapio) REFERENCES cardapio (id),
    CONSTRAINT unq_comanda_cardapio UNIQUE (id_comanda, id_cardapio)
);
